version: '3.8'

# Using Anchors for consistency across Airflow components
x-airflow-common: &airflow-common
  build: . # This tells Docker to use the Dockerfile in the current directory
  user: "50000:0"
  env_file: .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_airflow:5432/airflow_metadata
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SESSION_BACKEND: securecookie
    # Added /opt/airflow to ensure 'spark.schemas' is importable
    PYTHONPATH: /opt/airflow/include:/opt/airflow/dags:/opt/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./include:/opt/airflow/include
    - ./requirements.txt:/opt/airflow/requirements.txt
    - ./spark:/opt/airflow/spark
  networks:
    - data_platform_net

services:
  # 1. METADATA DB (Internal Airflow state)
  postgres_airflow:
    image: postgres:16-alpine
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow_metadata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d airflow_metadata" ]
      interval: 5s
      retries: 5
    networks:
      - data_platform_net

  # 2. AIRFLOW INIT (Runs once then exits)
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: >
      bash -c "airflow db migrate &&  airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
    depends_on:
      postgres_airflow:
        condition: service_healthy

  # 3. AIRFLOW WEBSERVER
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data_platform_net

  # 4. AIRFLOW SCHEDULER
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./spark:/opt/airflow/spark
      - ./spark/jars:/opt/airflow/spark/jars
    networks:
      - data_platform_net

  # 5. STORAGE (MinIO)
  minio:
    image: minio/minio
    container_name: minio_storage
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - data_platform_net

  # 6. PROCESSING (Spark Master)
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark_master
    user: root
    ports:
      - "8081:8080"
      - "7077:7077"
    command: >
      bash -c "cp /custom-jars/* /opt/spark/jars/ 2>/dev/null; /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    volumes:
      - ./spark/jars:/custom-jars
      - ./spark/jobs:/opt/spark/jobs
    networks:
      - data_platform_net

  # 7. PROCESSING (Spark Worker)
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark_worker
    user: root
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    depends_on:
      - spark-master
    command: >
      bash -c "cp /custom-jars/* /opt/spark/jars/ 2>/dev/null; /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    volumes:
      - ./spark/jars:/custom-jars
    networks:
      - data_platform_net

  # 7. DATA WAREHOUSE (Analytics DB)
  postgres_analytics:
    image: postgres:16-alpine
    container_name: postgres_analytics
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Exposed on different port to avoid conflict
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
    networks:
      - data_platform_net

  # 8. VISUALIZATION (Metabase)
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_viz
    depends_on:
      postgres_analytics:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres_analytics
    networks:
      - data_platform_net

networks:
  data_platform_net:
    driver: bridge
